/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface GalleryInfo {
  name: string
  icon: string
  tagName: string
}

export interface HapApp {
  name: string
  icon: string
  package: string
  category: string
}

export interface V1User {
  id: number
  nick: string
  face: string
  level: number
  member: string
}

export declare function displayClick(display: number, x: number, y: number): Promise<string>

export declare function fetchGallery(package: string): Promise<GalleryInfo>

export declare function hapVersion(port: number, pkg: string): Promise<string>

export declare function haps(port: number): Promise<Array<HapApp>>

export declare function shell(port: number, cmd: string): Promise<string>

export declare function v1Authorize(): Promise<string>

export declare function v1Login(token: string): Promise<V1User>

